"""Models module initialization."""

from app.models.database import (
    User,
    UserRole,
    Team,
    Wrestler,
    WrestlerStatus,
    Grade,
    Priority,
    OverviewMetrics,
    OverviewSeries,
    BodyCompositionMetrics,
    BodyCompositionSeries,
    BloodworkMetrics,
    BloodworkSeries,
    RecoveryMetrics,
    RecoverySeries,
    SupplementsMetrics,
    SupplementsSeries,
    PerformanceMetrics,
    PerformanceSeries,
    TrainingProgram,
    TrainingProgramBlock,
    TrainingProgramAIRecommendation,
    AIChartInsight,
    SectionScore,
    ScoreDriver,
    TokenBlacklist,
)

from app.models.legacy import (
    LegacyAthlete,
    SessionTime,
    LegacyMetric,
    BodyCompositionFS,
    BodyCompositionGR,
    ChestbeltHRGR,
    FitnessFS,
    UrionAnalysisGR,
)

__all__ = [
    # New API models
    "User",
    "UserRole",
    "Team",
    "Wrestler",
    "WrestlerStatus",
    "Grade",
    "Priority",
    "OverviewMetrics",
    "OverviewSeries",
    "BodyCompositionMetrics",
    "BodyCompositionSeries",
    "BloodworkMetrics",
    "BloodworkSeries",
    "RecoveryMetrics",
    "RecoverySeries",
    "SupplementsMetrics",
    "SupplementsSeries",
    "PerformanceMetrics",
    "PerformanceSeries",
    "TrainingProgram",
    "TrainingProgramBlock",
    "TrainingProgramAIRecommendation",
    "AIChartInsight",
    "SectionScore",
    "ScoreDriver",
    "TokenBlacklist",
    # Legacy Fittechno models
    "LegacyAthlete",
    "SessionTime",
    "LegacyMetric",
    "BodyCompositionFS",
    "BodyCompositionGR",
    "ChestbeltHRGR",
    "FitnessFS",
    "UrionAnalysisGR",
]
